version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/cvcourse-react-app
      dockerfile: Dockerfile
      args:
        VITE_SERVER_HOST: ${SERVER_HOST}
    ports:
      - "80:80"  # Проксируем порт 80 на хосте к порту 80 в контейнере
    environment:
      VITE_SERVER_HOST: ${SERVER_HOST}  # Переменная окружения для React приложения
    depends_on:
      - backend  # Frontend зависит от backend'a
    restart: always # Автоматический перезапуск при сбое
    # volumes:
    #   - ./frontend/cvcourse-react-app:/usr/share/nginx/html  # Только для разработки, hot reload
    #user: nginx  # В большинстве случаев это не нужно, лучше настроить внутри Dockerfile

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      YOOKASSA_SHOP_ID: ${YOOKASSA_SHOP_ID}
      YOOKASSA_SHOP_SECRET: ${YOOKASSA_SHOP_SECRET}

#networks:
#  default:
#    driver: bridge
