services:
  frontend:
    build:
      context: .
      dockerfile: /Dockerfile
    ports:
      - "4000:4000"
  
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
